server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/*]':
            allowed-origin-patterns: ''
            allowed-methods: ""
            allowed-headers: ""
            allow-credentials: true
      routes:
        - id: codigo-service
          uri: lb://codigo-service
          predicates:
            - Path=/codigo/**
        - id: prueba-service
          uri: lb://prueba-service
          predicates:
            - Path=/prueba/**
